global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scraper Service
  - job_name: 'scraper-service'
    static_configs:
      - targets: ['scraper-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis (if you want to monitor Redis)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
